### ISSUE TITLE
Corregir la altura de las imagenes de productos destacados.

### ISSUE THREAD

**Issue by emiarias** [ErikaCV/proyecto-final#44]
Proceso
Al ingresar a la página principal del proyecto.

Resultado esperado
Visualizar correctamente todos los datos de la página

Resultado actual
En la grilla con dos secciones de productos destacados los productos tienen alturas diferentes, solo se percibe el detalle en dispositivos grandes.

Captura
![image](https://github.com/ErikaCV/proyecto-final/assets/18445151/e5010157-7e58-4f2b-a7d3-4e380ca256c2)

**Comment by francojnieva** [comment]
La issue se solucionó agregando altura a las imágenes, la modificación garantiza que las imágenes se muestren correctamente en dispositivos  grandes.
