### ISSUE TITLE
Corregir el footer para que se visualice al final del sitio

### ISSUE THREAD

**Issue by emiarias** [ErikaCV/proyecto-final#45]
Proceso
Al ingresar a la página de login.

Resultado esperado
Visualizar correctamente todos los datos de la página

Resultado actual
El footer se ve arriba en las páginas donde el contenido es mejor a la altura del dispositivo. 

Captura
![image](https://github.com/ErikaCV/proyecto-final/assets/18445151/ebf779f4-b438-4b71-acfa-e95675f5a235)

**Comment by francojnieva** [comment]
La issue se ha resuelto al agregar altura mínima de 100vh al contenedor del formulario.  Esto hace que el footer se visualice sin mostrar un espacio en blanco por debajo de su posición.
