### ISSUE TITLE
Agregar un limite de caracteres en los formularios

### ISSUE THREAD

**Issue by emiarias** [ErikaCV/proyecto-final#46]
Proceso
Al ingresar a la página de login y cargar los datos del usuario.

Resultado esperado
Ingresar la cantidad correcta de caracteres.

Resultado actual
El formulario de login permite agregar cualquier cantidad de caracteres en el campo del email y del password, deberia tener un limite que coincida con la información que espera el backend.

Captura
![image](https://github.com/ErikaCV/proyecto-final/assets/18445151/b49eed2f-be9d-4c9a-a82d-c3e45db12791)

**Comment by francojnieva** [comment]
Se solucionó al agregar validaciones de: minLength y maxLength.
