### ISSUE TITLE
Error al agregar un nuevo producto

### ISSUE THREAD

**Issue by emiarias** [ErikaCV/proyecto-final#49]
Proceso
Al ingresar a la pagina de administrador y crear completar el formulario para agregar un producto.

Resultado esperado
Crear el producto cargado.

Resultado actual
El formulario muestra el error de completar todos los campos, aunque los datos estan cargados. El error deberia indicar que datos son incorrectos en caso de no permitir por ejemplo numeros negativos de precio y stock o un limite en la cantidad de caracteres

![image](https://github.com/ErikaCV/proyecto-final/assets/18445151/c6025d73-3d32-4f4b-96a3-38c3566447e2)
![image](https://github.com/ErikaCV/proyecto-final/assets/18445151/f6eb8c33-9908-4fa9-8392-cc8a624af5d9)

**Comment by francojnieva** [comment]
La issue se resolvió agregando validaciones a los campos del formulario.
 título, descripción y categoría tienen un máximo de caracteres.
 stock y precio no aceptan números negativos.
Los campos no deben estar vacíos
