### ISSUE TITLE
Error al visualizar un producto nuevo en la página del administrador

### ISSUE THREAD

**Issue by emiarias** [ErikaCV/proyecto-final#50]
Proceso
Luego de crear un producto nuevo desde la página del administrador.

Resultado esperado
Visualizar correctamente el nuevo producto en la tabla del administrador.

Resultado actual
La tabla del administrador no se actualiza automaticamente al crear el producto, el usuario debe actualizar a mano la pagina para poder visualizarlo. Ademas al no controlar la cantidad de caracteres maximos en el formulario de alta de producto, la tabla del administrador se rompe cuando cargamos mucha información.

![image](https://github.com/ErikaCV/proyecto-final/assets/18445151/e43785f0-3681-4adb-b487-324ba1600e4b)

**Comment by francojnieva** [comment]
El formulario para agregar productos ya cuenta con validaciones. Por lo tanto la tabla del administrador no se rompe y se aprecia correctamente.
