### ISSUE TITLE
El formulario para editar un producto no esta validado

### ISSUE THREAD

**Issue by emiarias** [ErikaCV/proyecto-final#51]
Proceso
Al ingresar al formulario para editar un producto desde la tabla del administrador

Resultado esperado
Modificar los datos del producto correctamente

Resultado actual
El formulario no tiene validaciones, se puede borrar el precio, la categoria, no tiene una cantidad de caracteres maximas, se puede agregar precios negativos, etc. Al editar un producto con valores negativos no funciona correctamente el carrito de compras.

![image](https://github.com/ErikaCV/proyecto-final/assets/18445151/a276d1a7-2976-4e4b-a569-36a8fd1df41f)
![image](https://github.com/ErikaCV/proyecto-final/assets/18445151/76a980a2-1897-4f59-a6c1-fb02a45a1fa3)

**Comment by francojnieva** [comment]
La issue se resolvió agregando en cada campo del formulario sus respectivas validaciones.
